### PR TITLE
Vogelnest integration

### PR DESCRIPTION
**Pull request by wanLo**
Modernizes on-boarding:

- [x]  Stops sending passwords, but creates JWT, as required by vogelnest API
- [x]  Updates links and text to reflect the current state of SOG tools
- [x]  Adds plain text to multipart massage to improve spam rating
- [ ]  JWT check implemented in dashboard-frontend and vogelnest (api)
- [ ]  Tested

### CODE REVIEW

**Comment by wanLo** [comment]
JWTs are created with https://github.com/adhocore/php-jwt

**Comment by marcelklehr** [comment]
Mmmh. I'd rather retire this whole repository and change https://github.com/studieren-ohne-grenzen/sogintegration.

**Comment by laurenzfg** [comment]
Hey @wanLo I am working right now on an improved sogintegration. I did not know about this pull request and your efforts to update the legacy dashboard.
I will use your email template, though. Or shall we continue to use the legacy one?

**Comment by wanLo** [comment]
Nah, as Marcel has said, we better build a new integration with vogelnest. Also, styled html mails like vogelnest is sending them now would be nice.

**Pull request closed without merging**
